version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:8.14.0
    container_name: elasticsearch-new
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata-new:/usr/share/elasticsearch/data

volumes:
  esdata-new:
    driver: local